# Generated by Django 3.2.3 on 2021-06-03 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_auto_20210509_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 13, 31, 59, 161032), null=True),
        ),
    ]
