# Generated by Django 3.2.3 on 2021-06-03 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0008_alter_userstory_story_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 13, 44, 26, 882236), null=True),
        ),
    ]
